export const GET_MOVIES_REQUEST = "MOVIES/GET/REQUEST";
export const GET_MOVIES_SUCCESS = "MOVIES/GET/SUCCESS";
export const GET_MOVIES_ERROR = "MOVIES/GET/ERROR";

export const DELETE_MOVIE_REQUEST = "MOVIES/DELETE/REQUEST";
export const DELETE_MOVIE_SUCCESS = "MOVIES/DELETE/SUCCESS";
export const DELETE_MOVIE_ERROR = "MOVIES/DELETE/ERROR";
